server:
  port: 6001

keycloak:
  enabled: true
  realm: key-web-login
  auth-server-url: http://localhost:8080/
  ssl-required: external
  resource: key-web-login-cli
  credentials:
    secret: 1ZGmkYnz97sR9nVBV5FKPSzuxIBCZlP7
  use-resource-role-mappings: true
  bearer-only: true